apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: default
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: backend
  ports:
  - port: {{ .Values.backend.service.port }}
    targetPort: 8000

